PROFILES = {
    "Dash Digital (@dashdgt)": {
        "key": "dashdgt",
        "handle": "@dashdgt",
        "name": "Dash Digital",
        "instagram_id": "17841465464445282",
        "facebook_account_id": "3730768157200767",
        "bio": "Agência de marketing digital especializada em tráfego pago para professores que querem lançar e escalar cursos online.",
        "tags": ["#TráfegoPago", "#LançamentoDeCursos", "#MarketingDigital", "#ProfessoresDigitais", "#MetaAds"],
        "avatar": "📊",
        "footer": "Relatório gerado para a <strong>Dash Digital</strong> por Dash Digital.",
        "colors": {
            "p": "#003f7c", "p2": "#1a5a9a", "a": "#f8b940", "ad": "#d99a20",
            "al": "rgba(248,185,64,0.13)", "pl": "rgba(0,63,124,0.08)",
            "bg": "#f0f3f8", "header_end": "#2471c8", "period_color": "#ffe08a",
            "stat_color": "#f8b940",
        },
    },
    "Questão de Texto (@questaodetexto)": {
        "key": "questaodetexto",
        "handle": "@questaodetexto",
        "name": "Questão de Texto",
        "instagram_id": "17841466194254352",
        "facebook_account_id": "2014012268996583",
        "bio": "Canal de conteúdo sobre língua portuguesa, redação e literatura — criando conexão com o aprendizado de forma leve e profunda.",
        "tags": ["#LínguaPortuguesa", "#Redação", "#Literatura", "#ENEM", "#Educação"],
        "avatar": "📝",
        "footer": "Relatório gerado para o <strong>Questão de Texto</strong> por Dash Digital.",
        "colors": {
            "p": "#323a92", "p2": "#4a54c7", "a": "#e960b2", "ad": "#c940a0",
            "al": "rgba(233,96,178,0.13)", "pl": "rgba(50,58,146,0.08)",
            "bg": "#f3f4fd", "header_end": "#5c68d8", "period_color": "#fbbe1b",
            "stat_color": "#e960b2",
        },
    },
    "Prof. Wanzeller (@prof.wanzeller)": {
        "key": "wanzeller",
        "handle": "@prof.wanzeller",
        "name": "Prof. Wanzeller",
        "instagram_id": "17841479657213211",
        "facebook_account_id": "1429787371828065",
        "bio": "Professor de matemática apaixonado por transformar alunos e criar professores de sucesso no digital.",
        "tags": ["#ProfessorDigital", "#Matemática", "#CursosOnline", "#EAD", "#Educação"],
        "avatar": "🎓",
        "footer": "Relatório gerado para o professor <strong>Wanzeller</strong> por Dash Digital.",
        "colors": {
            "p": "#0d2137", "p2": "#1a3a5c", "a": "#c9a227", "ad": "#a88520",
            "al": "rgba(201,162,39,0.13)", "pl": "rgba(13,33,55,0.08)",
            "bg": "#f0f2f5", "header_end": "#1e4a70", "period_color": "#fde68a",
            "stat_color": "#c9a227",
        },
    },
    "Prof. Wanderson (@professor_wandersonmelo)": {
        "key": "wanderson",
        "handle": "@professor_wandersonmelo",
        "name": "Prof. Wanderson Melo",
        "instagram_id": "17841410776971693",
        "facebook_account_id": "372281334793918",
        "bio": "Professor de língua portuguesa para concursos de alto nível — magistratura, MP, DPU, AGU e Polícia Federal.",
        "tags": ["#Português", "#ConcursoPublico", "#Magistratura", "#MinistérioPublico", "#LinguaPortuguesa"],
        "avatar": "📚",
        "footer": "Relatório gerado para o professor <strong>Wanderson</strong> por Dash Digital.",
        "colors": {
            "p": "#2c3a45", "p2": "#3e5263", "a": "#e1a185", "ad": "#c47d5e",
            "al": "rgba(225,161,133,0.15)", "pl": "rgba(44,58,69,0.08)",
            "bg": "#f4f2f0", "header_end": "#4a6278", "period_color": "#f5d0bc",
            "stat_color": "#e1a185",
        },
    },
}
